spring:
  datasource:
    # mysql useSSL=false消除警告SSL连接问题
    #url: jdbc:p6spy:mysql://81.68.219.210:3306/zlibrary?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://localhost:3306/zlibrary?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:p6spy:mysql://81.68.219.210:3306/zlibrary?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    #password: 1234Qwer.
    password: 123456

    #服务器
    #username: root
    #password: 1234Qwer.
  data:
    #mongoDB
    mongodb:
      username: root
      password:
      uri: mongodb://localhost:27017/zlibrary
  decorator:
    datasource:
      p6spy:
        logging: file
        log-file: spy.log
        log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)


# 配置mybatis-plus
# 配置扫描xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  #端口号
  port: 7070
  #项目名，如果不设定，默认是 /
  servlet:
    context-path: /zlibrary

#----------------swagger配置-----------------------
#swagger:
#  #生产环境改为false（改为false后swagger-ui.html则无法访问）
#  enable: true
##解决Swagger2 异常 NumberFormatException:For input string:""
#logging:
#  level:
#    io:
#      swagger:
#        models:
#          parameters:
#            AbstractSerializableParameter: ERROR

#----------------knife4j配置-----------------------
knife4j:
  enable: true
  documents:
    - group: MongoTest Group
      name: My Documents
      locations: classpath:wiki/*
  setting:
    # default lang
    language: zh-CN

    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: WUSY | [knife4j]

    # header
    enableHomeCustom: true
    homeCustomLocation: classpath:wiki/README.md

    # models
    enableSwaggerModels: true
    swaggerModelName: My Entity
  # 启动用户登录验证
  basic:
    enable: true
    username: root
    password: 123456

#自定义常量
myCustomConstants:

  #起始时间，默认2022/10/10 1665331200
  startTime: 1665331200

  #起始id
  id: 0

